#!/bin/bash

set -e

Usage="Usage: kube-watch-handle-channel <Event> <Channel>"

function main {
    local Event="$1"
    local Channel="$2"
    local ChannelPrev="${Channel}.prev"
    local ChannelData
    local ChannelDataPrev
    local ChannelDataDiff

    if [ -z "${Event}" ] || [ -z "${Channel}" ]; then usage; fi
    if [ "${Event}" != "c" ]; then return; fi

    ChannelData="$(tr -d '\0' <"${Channel}")"
    if [ -z "${ChannelData}" ]; then return; fi

    if [ ! -e "${ChannelPrev}" ]; then
        touch "${ChannelPrev}"
    fi

    ChannelDataPrev="$(tr -d '\0' <"${ChannelPrev}")"
    ChannelDataDiff="$(diff <(echo -en "${ChannelDataPrev}") \
                            <(echo -en "${ChannelData}") | tail -n +3)"

    if [ -n "${ChannelDataDiff}" ]; then
        echo -e "### Channel data ###\\n${ChannelData}\\n###"
        echo -e "### Channel data diff ###\\n${ChannelDataDiff}\\n###"

        echo "Handling channel data with $(handler)..."
        "$(handler)" "${Channel}" "${ChannelData}" "${ChannelDataPrev}"

        echo "${ChannelData}" > "${ChannelPrev}"
    fi

    true > "${Channel}"
}

function handler {
    cat "/var/run/kube-watch-config/handler"
}

function usage {
    >&2 echo "${Usage}"
    exit 2
}

main "$@"
