#!/bin/bash

set -e

Usage="Usage: kube-watch-handle-file <Event> <FileName>"

function main {
    local Event="$1"
    local FileName="$2"

    if [ -z "${Event}" ] || [ -z "${FileName}" ]; then usage; fi
    if [ "${Event}" != "x" ]; then return; fi

    echo "Handling change in ${FileName}..."
    cat "${FileName}" >> "$(channel)"
}

function channel {
    cat "/var/run/kube-watch-config/channel"
}

function usage {
    >&2 echo "${Usage}"
    exit 2
}

main "$@"
