#!/bin/bash

set -e

USAGE=$(cat <<EOF
Usage: kube-watch object <Type> <[Namespace/]Name> [Options]
       kube-watch file <FileName> [Options]
       kube-watch version

Options:
    -j,--jsonpath=<Jsonpath>  Path to the object field (default: {})
    -c,--channel=<Channel>    Channel (default: /var/run/kube-watch/channel)
    -h,--handler=<Handler>    Handler (default: /usr/share/kube-watch/handler)
EOF
)

function main {
    local TARGET="$1"
    local CHANNEL="/var/run/kube-watch/channel"
    local HANDLER="/usr/share/kube-watch/handler"
    local PIDS=()

    case "${TARGET}" in
        object)
            local OBJECT="$2"
            local NAMESPACED_NAME="$3"
            local NAMESPACE="${3%%/*}"
            local NAME="${3##*/}"
            local JSONPATH="{}"

            if [ -z "${OBJECT}" ] || [ -z "${NAME}" ]; then usage; fi

            if [ "${NAMESPACE}/${NAME}" != "${NAMESPACED_NAME}" ]; then
                NAMESPACE="$(namespace)"
            fi

            shift 3
        ;;
        file)
            local FILENAME="$2"

            if [ -z "${FILENAME}" ]; then usage; fi

            shift 2
        ;;
        version) cat /kube-watch-version ;;
        *) usage ;;
    esac

    for ARG in "$@"; do
        case "${ARG}" in
            -j=|--jsonpath=*) JSONPATH="${ARG#*=}" ;;
            -c=|--channel=*) CHANNEL="${ARG#*=}" ;;
            -h=|--handler=*) HANDLER="${ARG#*=}" ;;
            *) unknown_option "${ARG}" ;;
        esac
    done

    set_runtime_config handler "${HANDLER}"
    set_runtime_config channel "${CHANNEL}"
    create_channel "${CHANNEL}"

    watch_channel "${CHANNEL}"
    PIDS+=("$!")

    case "${TARGET}" in
        object) watch_object "${OBJECT}" "${NAMESPACE}" "${NAME}" \
                             "${JSONPATH}" "${CHANNEL}" ;;
        file) watch_file "${FILENAME}" "${CHANNEL}" ;;
    esac
    PIDS+=("$!")

    wait_watchers "${PIDS[@]}"
}

function watch_object {
    local OBJECT="$1"
    local NAMESPACE="$2"
    local NAME="$3"
    local JSONPATH="$4"
    local CHANNEL="$5"

    echo "Watching object ${OBJECT} ${NAMESPACE}/${NAME} ${JSONPATH}..."

    (while :; do
        kubectl get "${OBJECT}" "${NAME}" \
                --watch \
                --namespace "${NAMESPACE}" \
                --output jsonpath="${JSONPATH}" |
            tee "${CHANNEL}" > /dev/null
    done) &
}

function watch_file {
    local FILENAME="$1"
    local CHANNEL="$2"

    echo "Watching file ${FILENAME}..."

    cat "${FILENAME}" >> "${CHANNEL}"
    (while :; do
        inotifyd kube-watch-handle-file "${FILENAME}"
    done) &
}

function watch_channel {
    local CHANNEL="$1"

    echo "Watching channel ${CHANNEL}..."
    inotifyd kube-watch-handle-channel "${CHANNEL}" &
}

function wait_watchers {
    local PIDS=("$@")

    echo "Watchers will be terminated on main process SIGTERM or SIGINT."
    trap 'kill -TERM ${PIDS[@]}' SIGTERM SIGINT

    echo "Waiting for watchers (pids: ${PIDS[*]}) get terminated..."
    wait "${PIDS[@]}"
}

function create_channel {
    local CHANNEL="$1"

    echo "Creating channel ${CHANNEL}..."
    if [ ! -e "${CHANNEL}" ]; then
        mkdir -p "$(dirname "${CHANNEL}")"
        touch "${CHANNEL}"
    fi
}

function set_runtime_config {
    local KEY="$1"
    local VALUE="$2"

    echo "Setting ${KEY} ${VALUE}..."

    mkdir -p "$(runtime_config_dir)"
    echo "${VALUE}" > "$(runtime_config_dir)/${KEY}"
}
function runtime_config_dir {
    echo "/var/run/kube-watch-config"
}

function kubectl {
    local CACERT; CACERT="$(service_account)/ca.crt"
    local TOKEN; TOKEN="$(cat "$(service_account)/token")"

    /bin/kubectl --certificate-authority "${CACERT}" \
                 --token "${TOKEN}" \
                 "$@"
}

function service_account {
    echo "/var/run/secrets/kubernetes.io/serviceaccount"
}
function namespace {
    if [ -e "$(service_account)/namespace" ]; then
        cat "$(service_account)/namespace"
    else
        echo "default"
    fi
}

function usage {
    >&2 echo "${USAGE}"
    exit 2
}
function unknown_option {
    local OPTION="$1"
    >&2 echo "Unknown option: ${OPTION%%=*}"
    exit 2
}

main "$@"
