#!/bin/bash

set -e

USAGE="Usage: kube-watch-handle-channel <Event> <Channel>"

function main {
    local EVENT="$1"
    local CHANNEL="$2"
    local CHANNEL_PREV="${CHANNEL}.prev"
    local CHANNEL_DATA
    local CHANNEL_DATA_PREV
    local CHANNEL_DATA_DIFF

    if [ -z "${EVENT}" ] || [ -z "${CHANNEL}" ]; then usage; fi
    if [ "${EVENT}" != "c" ]; then return; fi

    CHANNEL_DATA="$(tr -d '\0' <"${CHANNEL}")"
    if [ -z "${CHANNEL_DATA}" ]; then return; fi

    if [ ! -e "${CHANNEL_PREV}" ]; then
        touch "${CHANNEL_PREV}"
    fi

    CHANNEL_DATA_PREV="$(tr -d '\0' <"${CHANNEL_PREV}")"
    CHANNEL_DATA_DIFF="$(diff <(echo -en "${CHANNEL_DATA_PREV}") \
                              <(echo -en "${CHANNEL_DATA}") | tail -n +3)"

    echo -e "### Channel data ###\\n${CHANNEL_DATA}\\n###"
    echo -e "### Channel data diff ###\\n${CHANNEL_DATA_DIFF}\\n###"

    if [ -n "${CHANNEL_DATA_DIFF}" ]; then
        echo "Handling channel data with $(handler)..."
        "$(handler)" "${CHANNEL}" "${CHANNEL_DATA}" "${CHANNEL_DATA_PREV}"

        echo "Saving channel data..."
        echo "${CHANNEL_DATA}" > "${CHANNEL_PREV}"
    fi

    echo "Cleaning channel..."
    true > "${CHANNEL}"
    echo "Done."
}

function handler {
    cat "/var/run/kube-watch-config/handler"
}

function usage {
    >&2 echo "${USAGE}"
    exit 2
}

main "$@"
